CREATE TABLE WORKERSAH(
     WORKER_ID INT,
	 FIRST_NAME VARCHAR(255),
	 LAST_NAME VARCHAR(255),
	 SALARY INT,
	 JOINING_DATE DATETIME,
	 DEPARTMENT VARCHAR(255));

CREATE TABLE BONUSSAH(
     WORKER_REF_ID INT,
	 BONUS_DATE DATETIME,
	 BONUS_AMOUNT INT);

CREATE TABLE TITLESAH(
     WORKER_ID INT,
	 WORKER_TITLE VARCHAR(255),
	 AFFECTED_FROM DATETIME);


INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('001', 'Monika', 'Arora', '100000', '2014-02-20 09:00:00', 'HR');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('002', 'Niharika', 'Verma', '80000', '2014-06-11 09:00:00', 'Admin');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('003', 'Vishal', 'Singhal', '300000', '2014-02-20 09:00:00', 'HR');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('004', 'Amitabh', 'Singh', '500000', '2014-02-20 09:00:00', 'Admin');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('005', 'Vivek', 'Bhati', '500000', '2014-06-11 09:00:00', 'Admin');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('006', 'Vipul', 'Diwan', '200000', '2014-06-11 09:00:00', 'Account');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('007', 'Satish', 'Kumar', '75000', '2014-01-20 09:00:00', 'Account');

INSERT INTO WORKERSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('008', 'Geetika', 'Chauhan', '90000', '2014-04-11 09:00:00', 'Admin');


INSERT INTO BONUSSAH (WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT)
VALUES ('1', '2016-02-20 00:00:00', '5000');

INSERT INTO BONUSSAH (WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT)
VALUES ('2', '2016-06-11 00:00:00', '3000');

INSERT INTO BONUSSAH (WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT)
VALUES ('3', '2016-02-20 00:00:00', '4000');

INSERT INTO BONUSSAH (WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT)
VALUES ('1', '2016-02-20 00:00:00', '4500');

INSERT INTO BONUSSAH (WORKER_REF_ID, BONUS_DATE, BONUS_AMOUNT)
VALUES('2', '2016-06-11 00:00:00', '3500');


INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('1', 'Manager', '2016-02-20 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('2', 'Executive', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('8', 'Executive', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('8', 'Executive', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('5', 'Manager', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('4', 'Asst.Manager', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('7', 'Executive', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('6', 'Lead', '2016-06-11 00:00:00');

INSERT INTO TITLESAH(WORKER_ID, WORKER_TITLE, AFFECTED_FROM)
VALUES ('3', 'Lead', '2016-06-11 00:00:00');


SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT
FROM WORKERSAH
WHERE DEPARTMENT='Admin';

SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT
FROM WORKERSAH
WHERE FIRST_NAME LIKE '%a%';

SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT
FROM WORKERSAH
WHERE FIRST_NAME LIKE '%a';

SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT
FROM WORKERSAH
WHERE FIRST_NAME LIKE '______h';

SELECT COUNT(DEPARTMENT)
FROM WORKERSAH
WHERE DEPARTMENT='Admin';

SELECT FIRST_NAME,LAST_NAME
FROM WORKERSAH
WHERE SALARY >= '50000' AND SALARY <= '1000000';

SELECT DEPARTMENT, COUNT(*) AS Total_Workers
FROM WORKERSAH
GROUP BY DEPARTMENT
ORDER BY Total_Workers DESC;

SELECT WORKERSAH.SALARY, WORKERSAH.FIRST_NAME, WORKERSAH.LAST_NAME, WORKERSAH.JOINING_DATE, WORKERSAH.DEPARTMENT, TITLESAH.WORKER_TITLE
FROM WORKERSAH
LEFT JOIN TITLESAH
ON WORKERSAH.WORKER_ID = TITLESAH.WORKER_ID
WHERE WORKER_TITLE = 'Manager';

SELECT WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT, COUNT(*) AS duplicate_count
FROM WORKERSAH
GROUP BY WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT
HAVING COUNT(*) > 1;

SELECT *
FROM (
  SELECT *, ROW_NUMBER() OVER (ORDER BY WORKER_ID) AS row_num
  FROM WORKERSAH
) AS subquery
WHERE row_num % 2 <> 0;

SELECT *
FROM WORKERSAH
WHERE WORKER_ID % 2 = 0;

SELECT TOP 10 *
FROM WORKERSAH
ORDER BY WORKER_ID DESC;

SELECT SALARY
FROM WORKERSAH
ORDER BY SALARY DESC
LIMIT 1 OFFSET 4;

SELECT SALARY
FROM (
  SELECT SALARY, RANK() OVER (ORDER BY Salary DESC) AS SalaryRank
  FROM WORKERSAH
) AS ranked_table
WHERE SalaryRank = 5;

SELECT e1.WORKER_ID, e1.SALARY, e2.WORKER_ID, e2.SALARY
FROM WORKERSAH e1
JOIN WORKERSAH e2 ON e1.salary = e2.salary
WHERE e1.WORKER_ID <> e2.WORKER_ID;

SELECT *
FROM (
  SELECT *, PERCENTILE_DISC(0.5) WITHIN GROUP (ORDER BY WORKER_ID) OVER () AS percentile
  FROM WORKERSAH
) AS subquery
WHERE percentile <= 0.5;

SELECT DEPARTMENT, COUNT(*) AS Total_People
FROM WORKERSAH
GROUP BY DEPARTMENT
HAVING COUNT(*) < 5;

SELECT e.DEPARTMENT, e.FIRST_NAME, e.SALARY
FROM WORKERSAH e
INNER JOIN (
  SELECT DEPARTMENT, MAX(SALARY) AS Max_Salary
  FROM WORKERSAH
  GROUP BY DEPARTMENT
) t
ON e.DEPARTMENT = t.DEPARTMENT AND e.SALARY = t.Max_Salary;

SELECT DEPARTMENT, SUM(SALARY) AS Total_Salary
FROM WORKERSAH
GROUP BY DEPARTMENT;

SELECT FIRST_NAME, LAST_NAME
FROM WORKERSAH
WHERE Salary = (
  SELECT MAX(Salary)
  FROM WORKERSAH
);
