--1.
CREATE TABLE WorkerSAH(
      WORKER_ID INT,
	  FIRST_NAME VARCHAR(255),
	  LAST_NAME VARCHAR(255),
	  SALARY INT,
	  JOINING_DATE DATE,
	  DEPARTMENT VARCHAR(255));

ALTER TABLE WorkerSAH
ALTER COLUMN DEPARTMENT VARCHAR(255)
GO
INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('1', 'Monika', 'Arora', '100000', '2014-01-20 09:00:00', 'HR');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('2', 'Niharika', 'Verma', '80000', '2014-06-11 09:00:00', 'Admin');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('3', 'Vishal', 'Singhal', '300000', '2014-02-20 09:00:00', 'HR');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('4', 'Amitabh', 'Singh', '500000', '2014-02-20 09:00:00', 'Admin');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('5', 'Vivek', 'Bhati', '500000', '2014-06-11 09:00:00', 'Admin');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('6', 'Vipul', 'Diwan', '200000', '2014-06-11 09:00:00', 'Account');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('7', 'Satish', 'Kumar', '75000', '2014-01-20 09:00:00', 'Account');

INSERT INTO WorkerSAH (WORKER_ID, FIRST_NAME, LAST_NAME, SALARY, JOINING_DATE, DEPARTMENT)
VALUES ('8', 'Geetika', 'Chauhan', '90000', '2014-04-11 09:00:00', 'Admin');

SELECT *
FROM WorkerSAH
--2.
SELECT FIRST_NAME AS WORKER_NAME
FROM  WorkerSAH
--3.
SELECT UPPER(FIRST_NAME)
FROM WorkerSAH
--4.
SELECT DISTINCT(DEPARTMENT)
FROM WorkerSAH
--5.
SELECT SUBSTRING(FIRST_NAME, 1, 3) AS EXTRACT_STRING
FROM WorkerSAH
--6.
SELECT DEPARTMENT
FROM WorkerSAH
--7.
SELECT DISTINCT(LEN(DEPARTMENT)) AS COL_LEN
FROM WorkerSAH
--8.
SELECT REPLACE(FIRST_NAME, 'a', 'A')
FROM WorkerSAH
--9.
SELECT CONCAT(FIRST_NAME, ' ', LAST_NAME) AS COMPLETE_NAME
FROM WorkerSAH
--10.
SELECT *
FROM WorkerSAH
ORDER BY FIRST_NAME ASC;
--11.
SELECT *
FROM WorkerSAH
ORDER BY FIRST_NAME ASC, DEPARTMENT DESC; 
--12.
SELECT * 
FROM WorkerSAH
WHERE FIRST_NAME IN ('Vipul','Satish');
--13.
SELECT *
FROM WorkerSAH
WHERE FIRST_NAME NOT IN ('Vipul','Satish');
--14.
SELECT *
FROM WorkerSAH
WHERE SALARY BETWEEN 100000 AND 500000;
--15.
SELECT *
FROM WorkerSAH
WHERE JOINING_DATE = '20140220 09:00:00';
--16.
SELECT COUNT(DEPARTMENT) AS ADMIN_COUNT
FROM WorkerSAH
WHERE DEPARTMENT = 'Admin';